package ec.com.control.acceso.model;
// default package
// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;

/**
 * Aplicacion generated by hbm2java
 */
@Entity
@Table(name = "CAS_APLICACION", uniqueConstraints = @UniqueConstraint(columnNames = "PREFIJO"))
@SequenceGenerator(name = "SEQ_SEG_APLICACION_GEN", sequenceName = "SEQ_CAS_APLICACION", allocationSize = 1)
@Audited
public class Aplicacion implements java.io.Serializable {

	private static final long serialVersionUID = 8685080160184303374L;
	private long codigo;
	private String prefijo;
	private String nombre;
	private String descripcion;
	private String tipo;
	private String url;
	private String estado;
	private List<Recurso> recursos = new ArrayList<Recurso>(0);
	private List<RolAplicacion> rolAplicacions = new ArrayList<RolAplicacion>(0);

	public Aplicacion() {
	}

	public Aplicacion(long codigo, String prefijo, String nombre, String tipo,
			String estado) {
		this.codigo = codigo;
		this.prefijo = prefijo;
		this.nombre = nombre;
		this.tipo = tipo;
		this.estado = estado;
	}

	public Aplicacion(long codigo, String prefijo, String nombre,
			String descripcion, String tipo, String url, String estado,
			List<Recurso> recursos, List<RolAplicacion> rolAplicacions) {
		this.codigo = codigo;
		this.prefijo = prefijo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.url = url;
		this.estado = estado;
		this.recursos = recursos;
		this.rolAplicacions = rolAplicacions;
	}

	@Id
	@GeneratedValue(generator = "SEQ_SEG_APLICACION_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "PREFIJO", unique = true, nullable = false, length = 3)
	public String getPrefijo() {
		return this.prefijo;
	}

	public void setPrefijo(String prefijo) {
		this.prefijo = prefijo;
	}

	@Column(name = "NOMBRE", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "TIPO", nullable = false, length = 3)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "URL", length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ESTADO", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aplicacion")
	public List<Recurso> getRecursos() {
		return this.recursos;
	}

	public void setRecursos(List<Recurso> recursos) {
		this.recursos = recursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aplicacion")
	public List<RolAplicacion> getRolAplicacions() {
		return this.rolAplicacions;
	}

	public void setRolAplicacions(List<RolAplicacion> rolAplicacions) {
		this.rolAplicacions = rolAplicacions;
	}

}
