package ec.com.control.acceso.model;
// default package
// Generated Nov 20, 2013 4:33:26 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * AsignacionUsuarioSede generated by hbm2java
 */
@Entity
@Table(name = "CAS_ASIGNACION_USUARIO_SEDE")
@SequenceGenerator(name = "SEG_ASIGNACION_USUARIO_SEDE_GEN", sequenceName = "SEQ_CAS_ASIGNACION_USUARIO_SED", allocationSize = 1)
@Audited
public class AsignacionUsuarioSede implements java.io.Serializable {

	private static final long serialVersionUID = 4276997527799111216L;
	private Long codigo;
	private Sede sede;
	private Usuario usuario;
	private Date fechaAsignacion;
	private Date fechaFinalizacion;

	public AsignacionUsuarioSede() {
	}

	public AsignacionUsuarioSede(Long codigo, Sede sede, Usuario usuario,
			Date fechaAsignacion) {
		this.codigo = codigo;
		this.sede = sede;
		this.usuario = usuario;
		this.fechaAsignacion = fechaAsignacion;
	}

	@Id
	@GeneratedValue(generator = "SEG_ASIGNACION_USUARIO_SEDE_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_SEDE", nullable = false)
	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_USUARIO", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_ASIGNACION", nullable = false, length = 11)
	public Date getFechaAsignacion() {
		return this.fechaAsignacion;
	}

	public void setFechaAsignacion(Date fechaAsignacion) {
		this.fechaAsignacion = fechaAsignacion;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FINALIZACION", nullable = true, length = 11)
	public Date getFechaFinalizacion() {
		return this.fechaFinalizacion;
	}

	public void setFechaFinalizacion(Date fechaFinalizacion) {
		this.fechaFinalizacion = fechaFinalizacion;
	}

}
