package ec.com.control.acceso.model;
// default package
// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;

/**
 * ClaveUsuario generated by hbm2java
 */
@Entity
@Table(name = "CAS_CLAVE_USUARIO", uniqueConstraints = @UniqueConstraint(columnNames = "COD_USUARIO"))
@SequenceGenerator(name = "SEQ_SEG_CLAVE_USUARIO_GEN", sequenceName = "SEQ_CAS_CLAVE_USUARIO", allocationSize = 1)
@Audited
public class ClaveUsuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long codigo;
	private Usuario usuario;
	private String clave;
	private Date fechaInicio;
	private Date fechaFin;
	private String estado;
	private String estadoFinalizacionClave;

	public ClaveUsuario() {
	}

	public ClaveUsuario(Long codigo, Usuario usuario, String clave,
			Date fechaInicio, String estado) {
		this.codigo = codigo;
		this.usuario = usuario;
		this.clave = clave;
		this.fechaInicio = fechaInicio;
		this.estado = estado;
	}

	public ClaveUsuario(Long codigo, Usuario usuario, String clave,
			Date fechaInicio, Date fechaFin, String estado) {
		this.codigo = codigo;
		this.usuario = usuario;
		this.clave = clave;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(generator = "SEQ_SEG_CLAVE_USUARIO_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_USUARIO", unique = true, nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "CLAVE", nullable = false)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", nullable = false, length = 23)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", length = 23)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "ESTADO", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "ESTADO_FIN_CLAVE", length = 1)
	public String getEstadoFinalizacionClave() {
		return estadoFinalizacionClave;
	}

	public void setEstadoFinalizacionClave(String estadoFinalizacionClave) {
		this.estadoFinalizacionClave = estadoFinalizacionClave;
	}

}
