package ec.com.control.acceso.model;
// default package
// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name = "CAS_RECURSO")
@SequenceGenerator(name = "SEQ_SEG_RECURSO_GEN", sequenceName = "SEQ_CAS_RECURSO", allocationSize = 1)
@Audited
public class Recurso implements java.io.Serializable {

	private static final long serialVersionUID = 2666962894699612697L;
	private Long codigo;
	private Recurso padre;
	private Aplicacion aplicacion;
	private String nombre;
	private String descripcion;
	private String url;
	private Integer nivel;
	private String estado;
	private List<Recurso> recursos = new ArrayList<Recurso>(0);
	private List<RolAplicacionRecurso> rolAplicacionRecursos = new ArrayList<RolAplicacionRecurso>(
			0);
	
	private boolean asignado;

	public Recurso() {
	}

	public Recurso(Long codigo, Recurso padre, Aplicacion aplicacion,
			String nombre, String url, Integer nivel, String estado) {
		this.codigo = codigo;
		this.padre = padre;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
		this.url = url;
		this.nivel = nivel;
		this.estado = estado;
	}

	public Recurso(Long codigo, Recurso padre, Aplicacion aplicacion,
			String nombre, String descripcion, String url, Integer nivel,
			String estado, List<Recurso> recursos,
			List<RolAplicacionRecurso> rolAplicacionRecursos) {
		this.codigo = codigo;
		this.padre = padre;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.url = url;
		this.nivel = nivel;
		this.estado = estado;
		this.recursos = recursos;
		this.rolAplicacionRecursos = rolAplicacionRecursos;
	}

	@Id
	@GeneratedValue(generator = "SEQ_SEG_RECURSO_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne
	@JoinColumn(name = "CODIGO_PADRE", nullable = true)
	public Recurso getPadre() {
		return this.padre;
	}

	public void setPadre(Recurso padre) {
		this.padre = padre;
	}

	@ManyToOne
	@JoinColumn(name = "CODIGO_APLICACION", nullable = false)
	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "URL", nullable = false, length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "NIVEL", nullable = false, precision = 1, scale = 0)
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "ESTADO", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "padre")
	public List<Recurso> getRecursos() {
		return this.recursos;
	}

	public void setRecursos(List<Recurso> recursos) {
		this.recursos = recursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recurso")
	public List<RolAplicacionRecurso> getRolAplicacionRecursos() {
		return this.rolAplicacionRecursos;
	}

	public void setRolAplicacionRecursos(
			List<RolAplicacionRecurso> rolAplicacionRecursos) {
		this.rolAplicacionRecursos = rolAplicacionRecursos;
	}

	@Transient
	public boolean isAsignado() {
		return asignado;
	}

	public void setAsignado(boolean asignado) {
		this.asignado = asignado;
	}

}
