package ec.com.control.acceso.model;
// default package
// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * RolAplicacionRecurso generated by hbm2java
 */
@Entity
@Table(name = "CAS_ROL_APLICACION_RECURSO")
@SequenceGenerator(name = "SEQ_SEG_ROL_APLICACION_RECURSO_GEN", sequenceName = "SEQ_CAS_ROL_APLICACION_RECURSO", allocationSize = 1)
@Audited
public class RolAplicacionRecurso implements java.io.Serializable {

	private static final long serialVersionUID = -846385389407239324L;
	private Long codigo;
	private Recurso recurso;
	private RolAplicacion rolAplicacion;
	private String estado;

	public RolAplicacionRecurso() {
	}

	public RolAplicacionRecurso(Long codigo, Recurso recurso,
			RolAplicacion rolAplicacion) {
		this.codigo = codigo;
		this.recurso = recurso;
		this.rolAplicacion = rolAplicacion;
	}

	public RolAplicacionRecurso(Long codigo, Recurso recurso,
			RolAplicacion rolAplicacion, String estado) {
		this.codigo = codigo;
		this.recurso = recurso;
		this.rolAplicacion = rolAplicacion;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(generator = "SEQ_SEG_ROL_APLICACION_RECURSO_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_RECURSO", nullable = false)
	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_ROL_APLICACION", nullable = false)
	public RolAplicacion getRolAplicacion() {
		return this.rolAplicacion;
	}

	public void setRolAplicacion(RolAplicacion rolAplicacion) {
		this.rolAplicacion = rolAplicacion;
	}

	@Column(name = "ESTADO", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
