package ec.com.control.acceso.model;
// default package
// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

import ec.com.control.acceso.resources.Constantes;

/**
 * RolAplicacion generated by hbm2java
 */
@Entity
@Table(name = "CAS_ROL_APLICACION")
@SequenceGenerator(name = "SEQ_SEG_ROL_APLICACION_GEN", sequenceName = "SEQ_CAS_ROL_APLICACION", allocationSize = 1)
@Audited
public class RolAplicacion implements java.io.Serializable {

	private static final long serialVersionUID = -7479265746227182404L;
	private Long codigo;
	private Aplicacion aplicacion=new Aplicacion() ;
	private String nombre;
	private String descripcion;
	private String estado="";
	@SuppressWarnings("unused")
	private boolean estadoActivo;
	private boolean asignado;
	private List<RolAplicacionRecurso> rolAplicacionRecursos = new ArrayList<RolAplicacionRecurso>(
			0);
	private List<UsuarioRolAplicacion> usuarioRolAplicacions = new ArrayList<UsuarioRolAplicacion>(
			0);

	public RolAplicacion() {
	}

	public RolAplicacion(Long codigo, Aplicacion aplicacion, String nombre) {
		this.codigo = codigo;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
	}

	public RolAplicacion(Long codigo, Aplicacion aplicacion, String nombre,
			String descripcion,
			List<RolAplicacionRecurso> rolAplicacionRecursos,
			List<UsuarioRolAplicacion> usuarioRolAplicacions) {
		this.codigo = codigo;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.rolAplicacionRecursos = rolAplicacionRecursos;
		this.usuarioRolAplicacions = usuarioRolAplicacions;
	}

	@Id
	@GeneratedValue(generator = "SEQ_SEG_ROL_APLICACION_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne
	@JoinColumn(name = "COD_APLICACION", nullable = false)
	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(mappedBy = "rolAplicacion")
	public List<RolAplicacionRecurso> getRolAplicacionRecursos() {
		return this.rolAplicacionRecursos;
	}

	public void setRolAplicacionRecursos(
			List<RolAplicacionRecurso> rolAplicacionRecursos) {
		this.rolAplicacionRecursos = rolAplicacionRecursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rolAplicacion")
	public List<UsuarioRolAplicacion> getUsuarioRolAplicacions() {
		return this.usuarioRolAplicacions;
	}

	public void setUsuarioRolAplicacions(
			List<UsuarioRolAplicacion> usuarioRolAplicacions) {
		this.usuarioRolAplicacions = usuarioRolAplicacions;
	}
	
	@Column(name = "ESTADO", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Transient
	public boolean isEstadoActivo() {
		return estado.equals(Constantes.REGISTRO_ACTIVO);
	}

	public void setEstadoActivo(boolean estadoActivo) {
		this.estadoActivo = estadoActivo;
	}
	
	@Transient
	public boolean isAsignado() {
		return asignado;
	}

	public void setAsignado(boolean asignado) {
		this.asignado = asignado;
	}
	
}
