package ec.com.control.acceso.model;
// default package
// Generated Nov 20, 2013 4:33:26 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "CAS_SEDE")
@SequenceGenerator(name = "SEQ_SEG_SEDE_GEN", sequenceName = "SEQ_CAS_SEDE", allocationSize = 1)
@Audited
public class Sede implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long codigo;
	private Sede sede;
	private String nombre;
	private String descripcion;
	private String nemonico;
	private String estado;
	private List<Sede> sedes = new ArrayList<Sede>(0);
	private List<AsignacionUsuarioSede> asignacionUsuarioSedes = new ArrayList<AsignacionUsuarioSede>(
			0);

	public Sede() {
	}

	public Sede(Long codigo, String nombre, String estado) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.estado = estado;
	}

	public Sede(Long codigo, Sede sede, String nombre, String descripcion,
			String nemonico, String estado, List<Sede> sedes,
			List<AsignacionUsuarioSede> asignacionUsuarioSedes) {
		this.codigo = codigo;
		this.sede = sede;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.nemonico = nemonico;
		this.estado = estado;
		this.sedes = sedes;
		this.asignacionUsuarioSedes = asignacionUsuarioSedes;
	}

	@Id
	@GeneratedValue(generator = "SEQ_SEG_SEDE_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEDE_SUPERIOR")
	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	@Column(name = "NOMBRE", nullable = false, length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "NEMONICO", length = 10)
	public String getNemonico() {
		return this.nemonico;
	}

	public void setNemonico(String nemonico) {
		this.nemonico = nemonico;
	}

	@Column(name = "ESTADO", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sede")
	public List<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(List<Sede> sedes) {
		this.sedes = sedes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sede")
	public List<AsignacionUsuarioSede> getAsignacionUsuarioSedes() {
		return this.asignacionUsuarioSedes;
	}

	public void setAsignacionUsuarioSedes(
			List<AsignacionUsuarioSede> asignacionUsuarioSedes) {
		this.asignacionUsuarioSedes = asignacionUsuarioSedes;
	}

}
