package ec.com.control.acceso.model;
// default package
// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "CAS_USUARIO", uniqueConstraints = {
		@UniqueConstraint(columnNames = "CELULAR"),
		@UniqueConstraint(columnNames = "IDENTIFICACION") })
@SequenceGenerator(name = "SEQ_SEG_USUARIO_GEN", sequenceName = "SEQ_CAS_USUARIO", allocationSize = 1)
@Audited
public class Usuario implements java.io.Serializable {

	private static final long serialVersionUID = -8622196233866959952L;
	private Long codigo;
	private String identificacion;
	private String nombres;
	private String apellidos;
	private Date fechaNacimiento;
	private String direccion;
	private String telefono;
	private String celular;
	private String correoElectronico;
	private String cambioClave;
	private String actualizacionDatos;
	private String tokenCambioClave;
	private Date fechaSolicitudClave;
	private Sede sede;
	private String estado;
	private List<ClaveUsuario> clavesUsuario = new ArrayList<ClaveUsuario>(0);
	private List<UsuarioRolAplicacion> usuarioRolAplicacions = new ArrayList<UsuarioRolAplicacion>(
			0);
	private List<AsignacionUsuarioSede> asignacionUsuarioSedes = new ArrayList<AsignacionUsuarioSede>(
			0);

	public Usuario() {
	}

	public Usuario(Long codigo, String celular, String cambioClave,
			String actualizacionDatos, String estado) {
		this.codigo = codigo;
		this.celular = celular;
		this.cambioClave = cambioClave;
		this.actualizacionDatos = actualizacionDatos;
		this.estado = estado;
	}

	public Usuario(Long codigo, String identificacion, String nombres,
			String apellidos, Date fechaNacimiento, String direccion, String telefono, String celular,
			String cambioClave, String actualizacionDatos, String estado,
			List<ClaveUsuario> clavesUsuarios,
			List<UsuarioRolAplicacion> usuarioRolAplicacions) {
		this.codigo = codigo;
		this.identificacion = identificacion;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.celular = celular;
		this.cambioClave = cambioClave;
		this.actualizacionDatos = actualizacionDatos;
		this.estado = estado;
		this.clavesUsuario = clavesUsuarios;
		this.usuarioRolAplicacions = usuarioRolAplicacions;
	}

	@Id
	@GeneratedValue(generator = "SEQ_SEG_USUARIO_GEN", strategy = GenerationType.SEQUENCE)
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "IDENTIFICACION", unique = true, length = 10)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "NOMBRES", length = 150)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "APELLIDOS", length = 150)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_NACIMIENTO", length = 23)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}
	
	@Column(name = "DIRECCION")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TELEFONO", length = 10)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "CELULAR", unique = true, nullable = false, length = 15)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "CAMBIO_CLAVE", nullable = false, length = 2)
	public String getCambioClave() {
		return this.cambioClave;
	}

	public void setCambioClave(String cambioClave) {
		this.cambioClave = cambioClave;
	}

	@Column(name = "ACTUALIZACION_DATOS", nullable = false, length = 2)
	public String getActualizacionDatos() {
		return this.actualizacionDatos;
	}

	public void setActualizacionDatos(String actualizacionDatos) {
		this.actualizacionDatos = actualizacionDatos;
	}

	@Column(name = "ESTADO", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	@Column(name = "CORREO_ELECTRONICO", nullable = false, length = 150)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public List<ClaveUsuario> getClavesUsuario() {
		return this.clavesUsuario;
	}

	public void setClavesUsuario(List<ClaveUsuario> clavesUsuario) {
		this.clavesUsuario = clavesUsuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public List<UsuarioRolAplicacion> getUsuarioRolAplicacions() {
		return this.usuarioRolAplicacions;
	}

	public void setUsuarioRolAplicacions(
			List<UsuarioRolAplicacion> usuarioRolAplicacions) {
		this.usuarioRolAplicacions = usuarioRolAplicacions;
	}

	@Column(name = "TOKEN_CAMBIO_CLAVE", nullable = false, length = 255)
	public String getTokenCambioClave() {
		return tokenCambioClave;
	}

	public void setTokenCambioClave(String tokenCambioClave) {
		this.tokenCambioClave = tokenCambioClave;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_SOLICITUD_CLAVE", length = 23)
	public Date getFechaSolicitudClave() {
		return fechaSolicitudClave;
	}

	public void setFechaSolicitudClave(Date fechaSolicitudClave) {
		this.fechaSolicitudClave = fechaSolicitudClave;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public List<AsignacionUsuarioSede> getAsignacionUsuarioSedes() {
		return this.asignacionUsuarioSedes;
	}

	public void setAsignacionUsuarioSedes(
			List<AsignacionUsuarioSede> asignacionUsuarioSedes) {
		this.asignacionUsuarioSedes = asignacionUsuarioSedes;
	}

	@ManyToOne
	@JoinColumn(name = "CODIGO_SEDE", nullable = false)
	public Sede getSede() {
		return sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

}
